import { Provider } from './provider'
import './reset.scss'
import type { Metadata } from 'next'
import { Starter } from './starter'


export const metadata: Metadata = {
  title: 'Cctv store',
  // description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <Starter>
            {children}
          </Starter>
        </Provider>
      </body>
    </html>
  )
}
